# Generated by Django 4.1.7 on 2023-03-02 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZodiacSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_name', models.CharField(max_length=11)),
                ('from_date', models.CharField(max_length=30)),
                ('to_date', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SignHoroscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_horoscope', models.TextField()),
                ('date', models.DateField()),
                ('sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zodiac.zodiacsigns')),
            ],
        ),
    ]
