# Generated by Django 4.1.7 on 2023-03-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zodiac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signhoroscope',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='zodiacsigns',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
