# Generated by Django 4.1.7 on 2023-03-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zodiac', '0002_signhoroscope_slug_zodiacsigns_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='zodiacsigns',
            name='sign_image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
