# Generated by Django 4.1.7 on 2023-03-06 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zodiac', '0003_zodiacsigns_sign_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ZodiacSigns',
            new_name='ZodiacSign',
        ),
    ]
