# Generated by Django 4.1.7 on 2023-03-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zodiac', '0004_rename_zodiacsigns_zodiacsign'),
    ]

    operations = [
        migrations.AddField(
            model_name='zodiacsign',
            name='sign_view',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
