# Generated by Django 4.1.7 on 2023-03-07 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zodiac', '0005_zodiacsign_sign_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signhoroscope',
            old_name='sign',
            new_name='sign_id',
        ),
    ]
